spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true   #页面表单Rest。
    contentnegotiation:
      favor-parameter: true  #开启请求参数内容协商模式

  #加载druid配置文件。
  profiles:
    include: druid,thymeleaf,redis,actuator,jwt


server:
  port: 8081

# 配置mybatis规则
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml  #全局配置文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml  #sql映射文件位置
  configuration:
    map-underscore-to-camel-case: true

#配置mybatis-plus
#输出sql语句。
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



