#spring:
#  redis:
#    port: 6379
#    host: 121.40.84.85
#    database: 0
#    timeout: 200000
#    lettuce:
#      pool:
#        max-active: 20
#        max-idle: 5
#        min-idle: 1
#        max-wait: -1
#
#

spring:
  redis:
    port: 6379
    host: localhost
  data:
    mongodb:
      uri: mongodb://localhost:27017/cloud

