spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true   #页面表单Rest。
    contentnegotiation:
      favor-parameter: true  #开启请求参数内容协商模式

  #加载druid配置文件。
  profiles:
    include: druid,thymeleaf,nosql,actuator,jwt


server:
  port: 8081

# 配置mybatis规则
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml  #全局配置文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml  #sql映射文件位置
  configuration:
    map-underscore-to-camel-case: true

#配置mybatis-plus
#输出sql语句。
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#log4j配置。
logging:
  config: classpath:log4j.properties


#aliyun pay
alipay:
  appId: 2021000120607625
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCBs5AjwVqOz4wewnT+Xukv5RM0qJ7rU8/vMyD67aAOSOSiXcSLw1r4sDv0iwirb+7JYKbjj+gVGk131Yw5nF+ELxEYorSVMNiBwGP8Vkx6++luu40LasVlYqJvojoQOlbJLos53wgN8qF4CimIc+C9uoemJgyUI6foDY1DpYhLpAI+uDJRBfOK/5fry69esO1MeRPivtH9QowJW7yII8JlkNoT1NX81WCihvZhDz57LAFA55APD7Z52I8jV+STH/ekwTzkgoh86cR23YcjD0uGGHT6pKECDbh1vDqvih1KdFXTUnHixkPUKBChZMI480CIcIU5/b8BangvgBCLyjPNAgMBAAECggEAMXBVsBtivm8EdTEgUVmyPyxtbrQbp44SA5aUqrFrQias5+sgITo88fCTWfqpOlf3SFGMK8/N4kVdZCFFSyx9CDC8roxOk1PEI2lHc4cdrf9aEnhxIfn39lZrnmvTAB6MuDECpvOJ6W8j91LAVB//ebKhREbaopkYxo5r2248jsARoC3RkNljpEhko8WBpMK7NCnfQoVdzxOMX2Os5I1lpG2y5V8+grHqitp5NqaRbwJA3A64br1NO5PUVj8NIbponvprbmXuusXH+i+kIpexYPVekW43t60uJ6IDO3UNG/XDLVGLsANozMmSywXHOVm/Ao6by0CbG8u76er6wRsWDQKBgQC5FaTerG3wFnO0U1VdW58qMpouOprKc5sEQzSneorBRxl7+Kb/gdRMDR/rs/BjBa1Q/l4Z7+2HUZQ2kDNg1iSElb/VnYa4umerQ9mb1jMvFV6HgT846Wi57fhNm8d3AE/et6rFT2Xps8B/ouuD3SXt30xyi/98IM+IHw07FYgsLwKBgQCzZZBKdt5eqffCECek0lZZ1jwI75eXIqu09QkqgniBsyXftY+AHN0ZFbHElIHxOCeiiPGNrTOLU79pnbbhQGTyZMdwD76MiY5WPEXhgD51nCN0NtQkiJ+GDyrq8Np9iLd9J0TAjZsawzJ01lZgyjOnUyfXLrOKeXu8eF9bLJk0wwKBgD0gFM8lizlbcOMBEpQ+ihZZl+nkmPJ7s5p4x474PZMPdC8pM532trJXM0+Yoa9SVKcHGvTd9EhYfOZ4QT+d+XmAK1bVK4UeqtY5FkkNOOI34HxIByU4kMm2+eZHqFx40efwKIn5auL/5ndAyx9Fjh09PfYmnj3UaDXAa5IzzkEpAoGAVSUSO9V5K1LebbP/LOJL662bpt4Yg7oH5wYZyJxOF7jwc+IXbsXERoCec9/MYLG3VhRLGWQoP6uLANTDFNvcTZN5eP1wAgHTlahbvnCAtI9b4G+ZdpGFrToLs6CHAufdtr/piL5s7GHS09NbAetWYsc79IyM2F9aVBSJpZtgR8MCgYEAmY682xd4mPlJo4Q6Ji5bnEGbURapWuxoUd6GGT1QVeLVrR2pUtv30ggEOgCxd7Tp4v0vmlI3HyZyC/J4TGKhq2vIvpWOExIYs5OhvFmHq7GyMDBRMH1l0LaIYUWTa/160s3GSZQ/y0DuF2lH+9oCD1k18Qj2qyOkRsIBDN1wQC0=
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgbOQI8Fajs+MHsJ0/l7pL+UTNKie61PP7zMg+u2gDkjkol3Ei8Na+LA79IsIq2/uyWCm44/oFRpNd9WMOZxfhC8RGKK0lTDYgcBj/FZMevvpbruNC2rFZWKib6I6EDpWyS6LOd8IDfKheAopiHPgvbqHpiYMlCOn6A2NQ6WIS6QCPrgyUQXziv+X68uvXrDtTHkT4r7R/UKMCVu8iCPCZZDaE9TV/NVgoob2YQ8+eywBQOeQDw+2ediPI1fkkx/3pME85IKIfOnEdt2HIw9Lhhh0+qShAg24dbw6r4odSnRV01Jx4sZD1CgQoWTCOPNAiHCFOf2/AWp4L4AQi8ozzQIDAQAB
  gateway: openapi.alipaydev.com
  returnUrl: http://localhost:8082/purchasefinish
  #支付成功的接口回调，我们还没写，先空着
  notifyUrl: http://5198y370g3.zicp.vip/tifai/pay/fallback